---
title: "Introduction"
author: "Meggi Varnai"
date: "3/22/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#Introduction

Proficiency in data science is increasingly required for research and practice across a wide range of environmental science fields. In this class, we will explore tools and best practices for working with large
environmental datasets primarily using the programming language R. You will use these tools to analyze a range of real-world environmental datasets.

Student Learning Outcomes
Upon successful completion of the course, students will be able to:
1. Describe the basic code, file, and data management skills required to efficiently and effectively
analyze environmental datasets of a range of sizes.
2. Apply linear regression, basic machine learning, trend analysis techniques to reveal patterns in
environmental data relevant to their field of study.
3. Actively distinguish and select appropriate levels of analysis and code complexity to answer the
questions they have about their data.
4. Create a scientific investigation from scratch using environmental data and the data science skills
taught in the course.